### ISSUE TITLE
Functional Issue - Taskr Forms crashes immediately after starting

### ISSUE THREAD

**Issue by paulvwarner** [msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps#17]
# Functional Issue Report

### Taskr Application Type
Xamarin.Forms app

### Description
Taskr Forms crashes immediately after starting when deployed as a release build to a physical Android device with the Company Portal app installed.  If the company portal isn't installed, the app starts successfully (but I assume that's just because some company portal integration code doesn't run in that case).  

Exception from the device logs:

```
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.microsoft.intune.taskr.xamarin, PID: 14179
    java.lang.RuntimeException: Unable to create application crc64215e6f1d57ca6a3e.TaskrApp: java.lang.ArrayStoreException: short cannot be stored in an array of type java.lang.Object[]
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4731)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.ArrayStoreException: short cannot be stored in an array of type java.lang.Object[]
        at $Proxy7.registerAuthenticationCallback(Unknown Source)
        at crc64215e6f1d57ca6a3e.TaskrApp.n_onMAMCreate(Native Method)
        at crc64215e6f1d57ca6a3e.TaskrApp.onMAMCreate(TaskrApp.java:25)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy6.onMAMCreate(Unknown Source)
        at com.microsoft.intune.mam.client.app.ApplicationBehaviorImpl.onCreate(ApplicationBehaviorImpl.java:141)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy5.onCreate(Unknown Source)
        at com.microsoft.intune.mam.client.app.MAMApplication$Impl.onCreate(MAMApplication.java:112)
        at com.microsoft.intune.mam.client.app.MAMApplication.onCreate(MAMApplication.java:57)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

I get the same error when trying to run a similar Xamarin Forms Android app where I'm also trying to integrate the Intune SDK.

### Code and Settings Changes
I downloaded the latest code, then updated the _placeholderClientID and _placeholderRedirectURI to valid values (for a registered app where I've verified MSAL authentication works).

### Repro Steps
*Steps to reproduce the behavior.*
1. download latest Taskr repository
2. update _placeholderClientID and _placeholderRedirectURI to valid values
3. build and run release build of Taskr Forms on an Android device that has the Company Portal app installed

### Expected Behavior
Taskr Forms app runs without crashing when Company Portal app is installed.

### Logs
Incident ID: VSNAFGEA 
[device logs.txt](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps/files/6780292/device.logs.txt)
[build logs.txt](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps/files/6780294/build.logs.txt)

### Device Information
Moto G (2nd Generation), 
running Android 6.0 (API level 23)

### Xamarin Information
Visual Studio for Mac (community) version 8.10.3 (build 15)

### Screenshots and Video
n/a

**Comment by meghandaly** [comment]
This is a known issue that is track via #11 and in the main Android MAM Xamarin SDK repository ([Known Issue: Blank screen on launch of Android LOB apps using Intune App SDK Xamarin Bindings #49](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/issues/49))

There is no ETA on a fix at this time.
